### ISSUE TITLE
Clarification needed: Can't Set Type of NPM Package

### ISSUE THREAD

**Issue by bdhack23** [comp426-2022-fall/assignments#1]
When creating the NPM package for the midterm, I am never given the prompt to set the "type" field. But when looking over everything to confirm it is correct, the "type" field has git instead of module. I'm not sure how to set this field, any help would be appreciated.

**Comment by bdhack23** [comment]
A TA said that she would contact the professor about this since they can't figure it out, but I haven't heard anything yet.

**Comment by naomi04** [comment]
Has this issue been resolved? It looks like the default config for init only lets you set the repository type.

**Comment by bdhack23** [comment]
Problem still not solved, but professor said that we will get around to figuring it out.

**Comment by kyle0509** [comment]
I also have the same problem.

**Comment by mjsherry** [comment]
I am having this issue as well!

**Comment by naomi04** [comment]
I ended up manually adding the field to the appropriate file and that seemed to do the trick!

**Comment by smelliskay** [comment]
^^^ I think this is just the solution. Sorry for the delay in response from the TAs but I think we misinterpreted the problem. You should be able to just manually add it to package.json and there shouldn't be any issues.

**Comment by camsimba** [comment]
The directions of the midterm exam state that you must have `type: 'module'` in `package.json`, whether that is entered by prompt or manually you must have it in the file. Be sure to follow the directions, as they are stated clearly. Let me know if you have any other issues or questions moving forward!

**Comment by bdhack23** [comment]
I already tried adding it in manually, it was one of the first things I tried to do to fix the issue. However it still did not work. :(
