### ISSUE TITLE
Autograder: [Final exam question] All attempted runs result in "This job failed"

### ISSUE THREAD

**Issue by cooperhc** [comp426-2022-fall/assignments#16]
If you think the autograder has a bug, go through this checklist:

- [ ] Did you search or read through the other issues on this repo to make sure there isn't already a related issue?
- [ ] Did you run and test your code on your local machine?
- [ ] Did your code execute without errors on your local machine?
- [ ] Did your code run as expected on your local machine?

None of the above, create an issue
------------------------------------------------------------------

Make sure to add **all the information needed to understand the error** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

#### Which autograder check is failing?

The autograder fails to run for every single commit of e02, including previous commits that had worked (including the initial commit)

#### What is happening?

When I attempt to run the autograder, it instantly results in "This job failed" with no other information

#### Failed workflow run URL

https://github.com/comp426-2022-fall/e02comp-cooperhc/actions/runs/3638226413/jobs/6140403565

#### What should be happening?

The autograder should run

#### Screenshots of your local test(s)

Not necessarily applicable, but all my tests are entirely functional locally. Virtually no changes were made between the last working commit and current commits, but that isn't what's causing this considering even the initial commit is failing to run when the autograder is reran

#### Why do you think the autograder is failing? 

Other assignments seem to be grading fine when I try to rerun them, so I am not sure

**Comment by jdmar3** [comment]
This should be fixed now. We ran into the action run limit for private repos. I upped it this morning.
