### ISSUE TITLE
Final Comprehensive Exam Autograder Question

### ISSUE THREAD

**Issue by bdhack23** [comp426-2022-fall/assignments#4]
For the comprehensive final exam, when the professor said that "there will be no assistance offered for the autograder" did he mean that the autograder will not give any feedback on what we did wrong AND it will not tell us how many points we got? Or will it give us one or the other?

**Comment by bdhack23** [comment]
Anyone know the answer to this? I was hoping the professor or TA might know, but if a fellow student knows, do tell me! :)

**Comment by jdmar3** [comment]
It will function just like the other autograders. When I say that no assistance will be offered, I mean that you are not to come to office hours for assistance with the final exam programming tasks.

**Comment by bdhack23** [comment]
@jdmar3 Ohhh okay thank you so much for the clarification on that! Thanks for keeping the autograder aspect for the final, it will be very helpful! 😄
