### ISSUE TITLE
Clarification needed: Demo Link

### ISSUE THREAD

**Issue by DheyaM** [comp426-2022-fall/assignments#5]
#### URL of file with confusing thing

https://github.com/comp426-2022-fall/assignments/blob/main/a99-rubric.md

#### Line number of confusing thing

Lines 49-51

#### What is confusing?
"In order to get credit for this, add a row to the table in the README here and make a pull request: https://github.com/comp426-2022-fall/a99-demos/edit/main/README.md."
I was wondering what table this step refers to for us to add our demo link. Additionally, the link provided (https://github.com/comp426-2022-fall/a99-demos/edit/main/README.md.") does not work - 404 error. I'd appreciate any guidance.

**Comment by jdmar3** [comment]
Yes this is missing. I need to make the repo public. I'll update this issue when it is there.

**Comment by DheyaM** [comment]
Thanks @jdmar3

**Comment by jdmar3** [comment]
This should be there now. Reopen this if it is not for some reason.
