### ISSUE TITLE
Comprehensive Final Task 4: Do we Need to Fill in Table?

### ISSUE THREAD

**Issue by bdhack23** [comp426-2022-fall/assignments#8]
For task 4 on the comprehensive exam, I was curious as to whether or not we are supposed to go through the stuff in the info.db file and put it into the table we create if one does not already exist. Or are we just supposed to create a blank table if a table does not already exist?

**Comment by jdmar3** [comment]
You just need the middleware to create a table with the requested columns if one does not exist.

**Comment by bdhack23** [comment]
Thank you for the clarification!
