### ISSUE TITLE
Clarification needed: Email confirmation after submitting the assessment

### ISSUE THREAD

**Issue by DheyaM** [comp426-2022-fall/assignments#9]
Hi! I just filled out the assessment for the group project. However, I did not receive an email confirming my submission as stated in the form. 
I have downloaded the PDF of my responses just in case. 
I was just wondering if there's a way to make sure that my submission went through.
Thank you!

**Comment by jdmar3** [comment]
Hrmm. It looks like your response came through just fine, but it did not send out an email. There was something weird with the email trigger, which I just fixed, so thank you for bringing it to my attention so quickly. 

![image](https://user-images.githubusercontent.com/2459227/205517270-87eaf904-30d6-4137-a464-ef1b21d28970.png)

If you follow the same survey link, it should show you a message telling you that you have already completed it.

**Comment by DheyaM** [comment]
Thank you. You're right, it showed that message when I followed the link.
